import { read, write, exists } from "../core/fs";
import { paths } from "../core/path";
import { getState, setState } from "../core/state";

export async function plan() {
  const state = await getState();

  if (!state.taskSet) {
    console.log("❌ No task defined. Run: ai task \"<description>\"");
    return;
  }

  if (!state.scopeSet) {
    console.log("❌ No scope defined. Run: ai scope <files>");
    return;
  }

  const taskContent = await read(paths.task);
  const scopeContent = await read(paths.scope);

  // Read stack info if available
  let stackInfo = "";
  if (await exists(paths.stack)) {
    const stackRaw = await read(paths.stack);
    const stackName = stackRaw.split("\n").filter(l => l.trim() && !l.startsWith("#"))[0]?.trim();
    if (stackName && stackName !== "not-set") {
      stackInfo = `\n## Stack: ${stackName}\n`;
    }
  }

  const planContent = `# PLAN

Generated: ${new Date().toISOString()}

## Task
${taskContent.replace("# TASK\n\n", "").trim()}

## Scope
${scopeContent.replace("# ACTIVE SCOPE\n\n", "").trim()}
${stackInfo}
## Steps

> Plan steps should be generated by the AI agent.
> Run \`ai run\` to execute this plan.

---

Status: PENDING
`;

  await write(paths.plan, planContent);
  await setState({ planGenerated: true, phase: "planned" });

  console.log("✅ Plan generated at ai/runtime/PLAN.md");
  console.log("   Review the plan, then run: ai run");
}
